demo_produit:
    resource: "@DemoBundle/Controller/ProduitController.php"
    type:     annotation

demo:
    resource: "@DemoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
